// <auto-generated />
using System;
using LabClinic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabClinic.Api.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20251010051415_InicialParametrosCompletos")]
    partial class InicialParametrosCompletos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LabClinic.Api.Data.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<string>("PrescriptionPath")
                        .HasColumnType("longtext")
                        .HasColumnName("prescription_path");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("schedule");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("appointment_list", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.AppointmentTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.ToTable("appointment_test_list", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Bono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bono");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("MontoBono")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_bono");

                    b.Property<string>("NombreBono")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_bono");

                    b.HasKey("Id");

                    b.ToTable("bono", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cargo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Funcion")
                        .HasColumnType("longtext")
                        .HasColumnName("funcion");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_cargo");

                    b.Property<string>("Requisito")
                        .HasColumnType("longtext")
                        .HasColumnName("requisito");

                    b.HasKey("Id");

                    b.ToTable("cargo", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.CategoryInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_insumo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("Id");

                    b.ToTable("categoriainsumo", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoCita")
                        .HasColumnType("int")
                        .HasColumnName("estado_cita")
                        .HasAnnotation("Relational:JsonPropertyName", "estado_cita");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdMedico")
                        .HasColumnType("int")
                        .HasColumnName("id_medico");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("id_paciente");

                    b.HasKey("Id");

                    b.ToTable("cita", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext")
                        .HasColumnName("contact");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.Property<string>("Middlename")
                        .HasColumnType("longtext")
                        .HasColumnName("middlename");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("client_list", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cotizacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_examen");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("cotizacion", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_descuento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto");

                    b.HasKey("Id");

                    b.ToTable("descuento", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .HasColumnType("longtext")
                        .HasColumnName("calle");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext")
                        .HasColumnName("numero");

                    b.Property<string>("Referencia")
                        .HasColumnType("longtext")
                        .HasColumnName("referencia");

                    b.Property<string>("Zona")
                        .HasColumnType("longtext")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("direccion", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dpi")
                        .HasColumnType("longtext")
                        .HasColumnName("DPI");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("FormacionAcademica")
                        .HasColumnType("longtext")
                        .HasColumnName("formacion_academica");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.HasKey("Id");

                    b.ToTable("empleado", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_examen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int?>("IdInsumo")
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdTipoExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_examen");

                    b.Property<string>("Resultado")
                        .HasColumnType("longtext")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.ToTable("examen", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.ExamenParametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_examen_parametro");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_examen");

                    b.Property<int>("IdParametro")
                        .HasColumnType("int")
                        .HasColumnName("id_parametro");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdExamen");

                    b.HasIndex("IdParametro");

                    b.ToTable("examen_parametro", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.FacturaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext")
                        .HasColumnName("Detalle");

                    b.Property<DateTime?>("FechaFactura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_factura");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_total");

                    b.Property<string>("Nit")
                        .HasColumnType("longtext")
                        .HasColumnName("NIT");

                    b.HasKey("Id");

                    b.ToTable("facturapago", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.FechaCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_fecha");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.HasKey("Id");

                    b.ToTable("fechacita", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.IngresoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ingreso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaExpira")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expira");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    b.HasKey("Id");

                    b.ToTable("ingresoinsumo", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacenado")
                        .HasColumnType("longtext")
                        .HasColumnName("almacenado");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_insumo");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_insumo");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("stock");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("longtext")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.ToTable("insumolaboratorio", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("municipio", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .HasColumnType("longtext")
                        .HasColumnName("concepto");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaGenerado")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_generado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdTipoPago")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_pago");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("Nota")
                        .HasColumnType("longtext")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_parametro");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTipoExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_examen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("TipoExamenId")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unidad");

                    b.Property<string>("ValorReferencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("valor_referencia");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoExamen");

                    b.HasIndex("TipoExamenId");

                    b.ToTable("parametro", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.ParametroExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_parametro_examen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_examen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<string>("RangoReferencia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rango_referencia");

                    b.Property<string>("Resultado")
                        .HasColumnType("longtext")
                        .HasColumnName("resultado");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.HasIndex("IdExamen");

                    b.ToTable("parametro_examen", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext")
                        .HasColumnName("correo");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int?>("IdDireccion")
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdDireccion")
                        .IsUnique();

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Planilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_planilla");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .HasColumnType("longtext")
                        .HasColumnName("banco");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechafin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechainicio");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int")
                        .HasColumnName("id_cargo");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<string>("NoCuenta")
                        .HasColumnType("longtext")
                        .HasColumnName("nocuenta");

                    b.Property<string>("Puesto")
                        .HasColumnType("longtext")
                        .HasColumnName("puesto");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("salariobase");

                    b.HasKey("Id");

                    b.ToTable("planilla", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.RegistroHorarioFecha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_registro");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("IdFecha")
                        .HasColumnType("int")
                        .HasColumnName("id_fecha");

                    b.HasKey("Id");

                    b.ToTable("registrohorariofechas", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_rol");

                    b.HasKey("Id");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext")
                        .HasColumnName("empresa");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("test_list", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.TipoExamen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_examen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.ToTable("tipoexamen", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.TipoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_tipo_pago");

                    b.HasKey("Id");

                    b.ToTable("tipopago", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firstname");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lastname");

                    b.Property<string>("Middlename")
                        .HasColumnType("longtext")
                        .HasColumnName("middlename");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LabClinic.Api.Data.Direccion", b =>
                {
                    b.HasOne("LabClinic.Api.Data.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_direccion_municipio");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("LabClinic.Api.Data.ExamenParametro", b =>
                {
                    b.HasOne("LabClinic.Api.Data.Examen", null)
                        .WithMany("Resultados")
                        .HasForeignKey("IdExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabClinic.Api.Data.Parametro", null)
                        .WithMany()
                        .HasForeignKey("IdParametro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LabClinic.Api.Data.Municipio", b =>
                {
                    b.HasOne("LabClinic.Api.Data.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("LabClinic.Api.Data.Parametro", b =>
                {
                    b.HasOne("LabClinic.Api.Data.TipoExamen", null)
                        .WithMany("Parametros")
                        .HasForeignKey("IdTipoExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabClinic.Api.Data.TipoExamen", "TipoExamen")
                        .WithMany()
                        .HasForeignKey("TipoExamenId");

                    b.Navigation("TipoExamen");
                });

            modelBuilder.Entity("LabClinic.Api.Data.ParametroExamen", b =>
                {
                    b.HasOne("LabClinic.Api.Data.Examen", "Examen")
                        .WithMany()
                        .HasForeignKey("IdExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("LabClinic.Api.Data.Person", b =>
                {
                    b.HasOne("LabClinic.Api.Data.Direccion", "Direccion")
                        .WithOne()
                        .HasForeignKey("LabClinic.Api.Data.Person", "IdDireccion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("LabClinic.Api.Data.User", b =>
                {
                    b.HasOne("LabClinic.Api.Data.Role", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LabClinic.Api.Data.Examen", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("LabClinic.Api.Data.TipoExamen", b =>
                {
                    b.Navigation("Parametros");
                });
#pragma warning restore 612, 618
        }
    }
}
